<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ConfigureAwait.Fody" Version="3.4.1" />
    <PackageVersion Include="Fody" Version="6.9.3" />
    <PackageVersion Include="LibGit2Sharp" Version="0.32.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.400" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.0" />
    <PackageVersion Include="NGitLab" Version="12.2.0" />
    <PackageVersion Include="NGitLab.Mock" Version="12.2.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="Verify.ClipboardAccept" Version="32.0.0" />
    <PackageVersion Include="Verify.MicrosoftLogging" Version="5.0.0" />
    <PackageVersion Include="Verify.XunitV3" Version="32.0.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
</Project>
