name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      id: semantic
      with:
        dry_run: true
        extends: |
          @semantic-release/commit-analyzer
          @semantic-release/release-notes-generator
          @semantic-release/github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set Build Version
      id: version
      run: |
        if [ -z $SEM_VER ]
        then
          echo "num=1.0.0" >> $GITHUB_OUTPUT
        else
          echo "num="$SEM_VER >> $GITHUB_OUTPUT
        fi
      env:
        SEM_VER: ${{ steps.semantic.outputs.new_release_version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore -p:VersionPrefix=${{ steps.version.outputs.num }}
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release -o .ci-nuget
    - name: Upload nupkg
      uses: actions/upload-artifact@v4.3.5
      with:
        name: nuget
        path: .ci-nuget/*.nupkg
        retention-days: 5
    - name: Semantic Release Tag
      if: ${{ steps.semantic.outputs.new_release_tag }}
      uses: cycjimmy/semantic-release-action@v4
      with:
        extends: |
          @semantic-release/commit-analyzer
          @semantic-release/release-notes-generator
          @semantic-release/github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
